### ISSUE TITLE
Hello World fails

### ISSUE THREAD

**Issue by rdebath** [bitwitch/brainfuck-interpreter#1]
This program should print "Hello World!"
``` bf
+[>[<-[]>+[>+++>[+++++++++++>][>]-[<]>-]]++++++++++<]>
>>>>>----.<<+++.<-..+++.<-.>>>.<<.+++.------.>-.<<+.<.
```

**Comment by bitwitch** [comment]
yes its true, i am not finished implementing the interpreter yet. it is just for fun. I am trying to figure out how to handle brackets.

**Comment by rdebath** [comment]
That's fine then, it seemed like you thought it was finished.

**Comment by bitwitch** [comment]
finally got back around to this and think i figured out brackets.
